[project]
name = "michael-j-mauboussin-twin"
version = "0.1.0"
description = "LLM Engineering for Michael J. Mauboussin"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "ipykernel>=6.29.5",
    "zenml>=0.71.0",
]
